version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskflow-sql-db
    ports:
      - "${MSSQL_PORT}:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - taskflow-network

volumes:
  mssql-data:
    driver: local

networks:
  taskflow-network:
    driver: bridge